#+HTML_HEAD: <style type="text/css"> <!--/*--><![CDATA[/*><!--*/ .title { display: none; } /*]]>*/--> </style>
#+OPTIONS: num:nil

* Alumnos del centro
** Programas académicos
*** Programas internacionales
**** Erasmus+
El programa Erasmus+ ofrece la oportunidad al alumno de cursar parte de sus estudios en una de las universidades con las que tiene acuerdo la ETSIINF. La estancia dura entre 3 y 12 meses, la universidad de destino suele ofrecer alojamiento y se proporciona una ayuda mensual. [[http://www2.upm.es/portal/site/institucional/menuitem.e29ff8272ddfb41943a75910dffb46a8/?vgnextoid=99cd56b1540be110VgnVCM10000009c7648aRCRD][(más detalles)]]
***** [[http://fi.upm.es][Convocatoria k]]
***** [[http://www.fi.upm.es][Convocatoria k-1]]
**** Magalhães - SMILE
El programa Magalhães es una red entre Europa, Latinoamérica y Caribe cuyo objetivo es fomentar la movilidad y cooperación entre las universidades participantes. SMILE es el programa de movilidad de estudiantes dentro de Magalhães. Es similar al programa ERASMUS. La UPM es miembro de esta red y la ETSIINF participa en ella a través de acuerdos bilaterales con universidades latinoamericanas de reconocido prestigio.
***** [[http://fi.upm.es][Convocatoria k]]
***** [[http://www.fi.upm.es][Convocatoria k-1]]
**** Programa Global E3
Global E3 es un programa de intercambio para estudiantes de ingeniería. Se ofrece a los alumnos como oportunidad de cursar parte de sus estudios en una de las universidades asociadas. Está dirigido a alumnos con excelente aprovechamiento académico.
***** [[http://www2.upm.es/portal/site/institucional/menuitem.e29ff8272ddfb41943a75910dffb46a8/?vgnextoid=049f56b1540be110VgnVCM10000009c7648aRCRD][Descripción detallada y convocatorias]]
**** Programa de movilidad hispano-chino
La UPM mantiene acuerdos bilaterales con diversas universidades chinas con el objetivo de fomentar la movilidad de estudiantes entre ambos países. El programa está especialmente dirigido a la realización del trabajo fin de grado o de fin de master.
***** [[http://fi.upm.es][Convocatoria k]]
***** [[http://fi.upm.es][Convocatoria k-1]]
**** Programa indio-español
ENLACE NO FUNCIONA
***** Descripción
***** Convocatoria k
***** Convocatoria k-1
**** Convocatoria de proyectos de fin de carrera para el desarrollo
Sigue existiendo?
***** Descripción
***** Convocatoria k
***** Convocatoria k-1
**** Convocatoria de ayudas de viaje de cooperación
[Hacer una pequeña Descripción]
***** [[http://www.upm.es/institucional/Estudiantes/Movilidad/Programas_Internacionales/Ayudas_Viaje_Coop_1][1-4 meses]]
***** [[http://www.upm.es/institucional/Estudiantes/Movilidad/Programas_Internacionales/Ayudas_Viaje_Coop_2][4-6 meses]]
**** Programas de estancias cortas
***** Athens
El programa ATHENS consta de una serie de cursos organizados en universidades tecnológicas europeas, con reconocimiento de créditos y posibilidad de solicitar bolsa de viaje para acudir a los cursos en otros países. Hay una convocatoria de marzo y una de noviembre en cada curso. (más detalles o bien en la [[http://www.upm.es/Estudiantes/Movilidad/Programas_Internacionales/Athens][página de UPM]] o en la [[http://athensnetwork.eu/][página oficial de ATHENS]])
****** [[https://fi.upm.es][Convocatoria k]]
****** [[http://www.fi.upm.es][Convocatoria k-1]]
***** BEST
BEST (Board of European Students of Technology) es una organización apolítica y sin ánimo de lucro que ofrece cursos de corta duración y competiciones por Europa. [[http://www.best.eu.org/index.jsp][(más detalles)]]
*** Programa nacional SICUE
El programa SICUE permite la realización de parte de los estudios en otra universidad española, con garantía de reconocimiento académico y de aprovechamiento, así como adecuación al perfil curricular.
**** [[http://fi.upm.es][Convocatoria k]]
**** [[http://www.fi.upm.es][Convocatoria k-1]]
*** Acuerdos bilaterales y acuerdos de doble diploma de máster
La ETSIINF mantiene acuerdos de cooperación y acuerdos bilaterales con diversos centros extranjeros. Algunos de ellos permiten actividades de movilidad de tipo académico, doble diploma, de investigación, etc. Se listan en las páginas de cada convocatoria, a seguir:
**** [[http://www.fi.upm.es][Convocatoria k]]
**** [[http://www.fi.upm.es][Convocatoria k-1]]
*** Becas para estancias cortas de investigación en el MIT
Esta convocatoria está orientada a promover la relación con el Massachusetts Institute of Technology (MIT) mediante becas para estancias cortas de investigación de estudiantes de máster y de último curso de grado. [[http://www.upm.es/Estudiantes/BecasAyudasPremios/Becas/Becas_Movilidad?id=35d6e50734841510VgnVCM10000009c7648a____&fmt=detail&prefmt=articulo][(más detalles)]]
*** Programa de movilidad en investigación en Berkeley
asdasd
as
da
sd
asdasdsd
asd
as
d
asd
a
ds
*** Becas Tokyo Institute of Technology (Japón)
La UPM tiene un acuerdo con el Tokyo Institute of Technology Graduate School of Engineering de intercambio de estudiantes para la realización de estancias de investigación en su Summer Exchange Research Program. Son estancias de hasta 3 meses durante los meses de verano. [[http://www.upm.es/Estudiantes/BecasAyudasPremios/Becas/Becas_Movilidad?fmt=detail&prefmt=articulo&id=cd29e527e027c310VgnVCM10000009c7648a][(más detalles)]]
*** Becas Iberoamérica. Estudiantes de grado. Santander Universidades
Estas becas tienen por objeto fomentar la movilidad internacional de estudiantes de grado con el fin de realizar estudios en universidades iberoamericanas con las que la UPM tenga establecido un convenio internacional para el intercambio académico de estudiantes. [[http://www.upm.es/Estudiantes/BecasAyudasPremios/Becas/Becas_Movilidad?id=f6512dcb05ebf210VgnVCM10000009c7648a____&fmt=detail&prefmt=articulo][(más detalles)]]
*** Becas Iberoamérica. Santander Investigación
Estas becas tienen por objeto reforzar la movilidad e intercambio de alumnos de doctorado entre universidades y centros de investigación iberoamericanos con el fin de promover la actualización del nivel de conocimientos de los participantes, el aprendizage de nuevas técnicas y métodos y la consolidación de vínculos académicos. La duración mínima es de 4 meses. [[http://www.upm.es/Estudiantes/BecasAyudasPremios/Becas/Becas_Movilidad?id=3aabcc08ad1e3510VgnVCM10000009c7648a____&fmt=detail&prefmt=articulo][(más detalles)]]
** Programas de prácticas en empresa en el exterior
*** Vulcanus
El programa consiste en la realización de prácticas en Japón. Empieza en Septiembre y termina en Agosto del año siguiente. [[http://www2.upm.es/portal/site/institucional/menuitem.e29ff8272ddfb41943a75910dffb46a8/?vgnextoid=a23056b1540be110VgnVCM10000009c7648aRCRD][(más información)]]
*** Becas ARGO
ARGO es un programa de movilidad promovido por el Ministerio de Educación, Cultura y Deporte, cuyo objetivo es impulsar la formación complementaria de los titulados de todas las universidades españolas a través de la realización de prácticas en empresas de Europa, de EE.UU., Canadá y empresas españolas o multinacionales con sede en Asia u Oceanía. [[http://www.becasargo.es/][(más información)]]
*** Becas Faro Global
El programa de becas Faro Global promueve la movilidad de estudiantes de último curs mediante la realización de prácticas en empresas de Europa, Asia, Estados Unidos y Canadá. [[http://www.upm.es/Estudiantes/BecasAyudasPremios/Becas/Becas_Movilidad?fmt=detail&prefmt=articulo&id=8c56765ef9de1210VgnVCM10000009c7648a][(más información)]]
*** Becas Goya-Mundus
Las becas Goya-Mundus de la Comunidad de Madrid ofrecen a los estudiantes la oportunidad de realizar un período de prácticas en empresas/instituciones de Europa, Estados Unidos y Asia. [[http://www.upm.es/Estudiantes/BecasAyudasPremios/Becas/Becas_Movilidad?fmt=detail&prefmt=articulo&id=ced5765ef9de1210VgnVCM10000009c7648a][(más información)]]
*** Movilidad para prácticas en empresas a través del programa ERASMUS
El programa Erasmus+, además de ofrecer la oportunidad de realización de movilidad académica, también ofrece soporte a la movilidad para realización de prácticas en empresa.
**** [[http://www.upm.es/Estudiantes/Movilidad/Programas_Internacionales/Erasmus?fmt=detail&prefmt=articulo&id=395781ed1a8fb510VgnVCM10000009c7648a][Convocatoria 2017-2018]]
** Otros programas
*** Programas de voluntariado
La UPM también ofrece una serie de programas de voluntariado. Para un listado completo, visite [[http://www2.upm.es/portal/site/institucional/menuitem.e29ff8272ddfb41943a75910dffb46a8/?vgnextoid=7b26bfaaa7230210VgnVCM10000009c7648aRCRD][esta página]].
** Información de interés sobre idiomas
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Voy por aqui
Explicar mejor la necesidad de esta parte
*** PROLINTER
*** Programa de Formación linguística para los participantes en los programas de movilidad
*** Exámenes de acreditación externa TOEIC/TFI
*** Lenguas del mundo en B-learning
*** Certificados reconocidos nacional e internacionalmente
- Inglés
- Alemán
- Francés
- ...???
