#+HTML_HEAD: <style type="text/css"> <!--/*--><![CDATA[/*><!--*/ .title { display: none; } /*]]>*/--> </style>
#+OPTIONS: num:nil

* Alumnos del centro
** Programas académicos
*** Programas internacionales
**** Erasmus+
El programa Erasmus+ ofrece la oportunidad al alumno de cursar parte de sus estudios en una de las universidades con las que tiene acuerdo la ETSIINF. La estancia dura entre 3 y 12 meses, la universidad de destino suele ofrecer alojamiento y se proporciona una ayuda mensual. [[http://www2.upm.es/portal/site/institucional/menuitem.e29ff8272ddfb41943a75910dffb46a8/?vgnextoid=99cd56b1540be110VgnVCM10000009c7648aRCRD][(más detalles)]]
***** [[http://fi.upm.es][Convocatoria k]]
***** [[http://www.fi.upm.es][Convocatoria k-1]]
**** Magalhães - SMILE
El programa Magalhães es una red entre Europa, Latinoamérica y Caribe cuyo objetivo es fomentar la movilidad y cooperación entre las universidades participantes. SMILE es el programa de movilidad de estudiantes dentro de Magalhães. Es similar al programa ERASMUS. La UPM es miembro de esta red y la ETSIINF participa en ella a través de acuerdos bilaterales con universidades latinoamericanas de reconocido prestigio.
***** [[http://fi.upm.es][Convocatoria k]]
***** [[http://www.fi.upm.es][Convocatoria k-1]]
**** Programa Global E3
Global E3 es un programa de intercambio para estudiantes de ingeniería. Se ofrece a los alumnos como oportunidad de cursar parte de sus estudios en una de las universidades asociadas. Está dirigido a alumnos con excelente aprovechamiento académico.
***** [[http://www2.upm.es/portal/site/institucional/menuitem.e29ff8272ddfb41943a75910dffb46a8/?vgnextoid=049f56b1540be110VgnVCM10000009c7648aRCRD][Descripción detallada y convocatorias]]
**** Programa de movilidad hispano-chino
La UPM mantiene acuerdos bilaterales con diversas universidades chinas con el objetivo de fomentar la movilidad de estudiantes entre ambos países. El programa está especialmente dirigido a la realización del trabajo fin de grado o de fin de master.
***** [[http://fi.upm.es][Convocatoria k]]
***** [[http://fi.upm.es][Convocatoria k-1]]
**** Programa indio-español
ENLACE NO FUNCIONA
***** Descripción
***** Convocatoria k
***** Convocatoria k-1
**** Convocatoria de proyectos de fin de carrera para el desarrollo
Sigue existiendo?
***** Descripción
***** Convocatoria k
***** Convocatoria k-1
**** Convocatoria de ayudas de viaje de cooperación
[Hacer una pequeña Descripción]
***** [[http://www.upm.es/institucional/Estudiantes/Movilidad/Programas_Internacionales/Ayudas_Viaje_Coop_1][1-4 meses]]
***** [[http://www.upm.es/institucional/Estudiantes/Movilidad/Programas_Internacionales/Ayudas_Viaje_Coop_2][4-6 meses]]
**** Programas de estancias cortas
***** Athens
El programa ATHENS consta de una serie de cursos organizados en universidades tecnológicas europeas, con reconocimiento de créditos y posibilidad de solicitar bolsa de viaje para acudir a los cursos en otros países. Hay una convocatoria de marzo y una de noviembre en cada curso. (más detalles o bien en la [[http://www.upm.es/Estudiantes/Movilidad/Programas_Internacionales/Athens][página de UPM]] o en la [[http://athensnetwork.eu/][página oficial de ATHENS]])
****** [[https://fi.upm.es][Convocatoria k]]
****** [[http://www.fi.upm.es][Convocatoria k-1]]
***** BEST
BEST (Board of European Students of Technology) es una organización apolítica y sin ánimo de lucro que ofrece cursos de corta duración y competiciones por Europa. [[http://www.best.eu.org/index.jsp][(más detalles)]]
*** Programa nacional SICUE
El programa SICUE permite la realización de parte de los estudios en otra universidad española, con garantía de reconocimiento académico y de aprovechamiento, así como adecuación al perfil curricular.
**** [[http://fi.upm.es][Convocatoria k]]
**** [[http://www.fi.upm.es][Convocatoria k-1]]
*** Acuerdos bilaterales y acuerdos de doble diploma de máster
La ETSIINF mantiene acuerdos de cooperación y acuerdos bilaterales con diversos centros extranjeros. Algunos de ellos permiten actividades de movilidad de tipo académico, doble diploma, de investigación, etc. Se listan en las páginas de cada convocatoria, a seguir:
**** [[http://www.fi.upm.es][Convocatoria k]]
**** [[http://www.fi.upm.es][Convocatoria k-1]]
*** Becas para estancias cortas de investigación en el MIT
Esta convocatoria está orientada a promover la relación con el Massachusetts Institute of Technology (MIT) mediante becas para estancias cortas de investigación de estudiantes de máster y de último curso de grado. [[http://www.upm.es/Estudiantes/BecasAyudasPremios/Becas/Becas_Movilidad?id=35d6e50734841510VgnVCM10000009c7648a____&fmt=detail&prefmt=articulo][(más detalles)]]
*** Becas Tokyo Institute of Technology (Japón) SEGUIR A PARTIR DE AQUI!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
**** Descripción
**** Convocatoria k
Enlace a upm.es
*** Becas Iberoamérica - Santander Universidades - son becas o programas académicos?
*** Becas fórmula Santander - son becas o programas académicos?
*** Becas Santander-CRUE de movilidad Iberoamericana - son becas o programas académicos?
*** Becas UPM-Santander - son becas o programas académicos?
** Programas de prácticas en empresa en el exterior
*** Vulcanus
*** Becas ARGO
*** Becas Faro Global
*** Becas Goya-Mundus
*** Movilidad para prácticas en empresas a través del programa ERASMUS
**** Plataforma para ofertas de prácticas ERASMUS+
** Otros programas
*** Programas de voluntariado
** Información de interés sobre idiomas
Explicar mejor la necesidad de esta parte
*** PROLINTER
*** Programa de Formación linguística para los participantes en los programas de movilidad
*** Exámenes de acreditación externa TOEIC/TFI
*** Lenguas del mundo en B-learning
*** Certificados reconocidos nacional e internacionalmente
- Inglés
- Alemán
- Francés
- ...???
