#+HTML_HEAD: <style type="text/css"> <!--/*--><![CDATA[/*><!--*/ .title { display: none; } /*]]>*/--> </style>
#+OPTIONS: num:nil

* Alumnos del centro
** Programas académicos
*** Programas internacionales
**** Erasmus+
El programa Erasmus+ ofrece la oportunidad al alumno de cursar parte de sus estudios en una de las universidades con las que tiene acuerdo la ETSIINF. La estancia dura entre 3 y 12 meses, la universidad de destino suele ofrecer alojamiento y se proporciona una ayuda mensual.
***** [[http://fi.upm.es][Convocatoria k]]
***** [[http://www.fi.upm.es][Convocatoria k-1]]
**** Magalhães - SMILE
El programa Magalhães es una red entre Europa, Latinoamérica y Caribe cuyo objetivo es fomentar la movilidad y cooperación entre las universidades participantes. SMILE es el programa de movilidad de estudiantes dentro de Magalhães. Es similar al programa ERASMUS. La UPM es miembro de esta red y la ETSIINF participa en ella a través de acuerdos bilaterales con universidades latinoamericanas de reconocido prestigio.
***** [[http://fi.upm.es][Convocatoria k]]
***** [[http://www.fi.upm.es][Convocatoria k-1]]
**** Programa Global E3
Global E3 es un programa de intercambio para estudiantes de ingeniería. Se ofrece a los alumnos como oportunidad de cursar parte de sus estudios en una de las universidades asociadas. Está dirigido a alumnos con excelente aprovechamiento académico.
***** [[http://www2.upm.es/portal/site/institucional/menuitem.e29ff8272ddfb41943a75910dffb46a8/?vgnextoid=049f56b1540be110VgnVCM10000009c7648aRCRD][Descripción detallada y convocatorias]]
**** Programa de movilidad hispano-chino
La UPM mantiene acuerdos bilaterales con diversas universidades chinas con el objetivo de fomentar la movilidad de estudiantes entre ambos países. El programa está especialmente dirigido a la realización del trabajo fin de grado o de fin de master.
***** [[http://fi.upm.es][Convocatoria k]]
***** [[http://fi.upm.es][Convocatoria k-1]]
**** Programa indio-español
ENLACE NO FUNCIONA
***** Descripción
***** Convocatoria k
***** Convocatoria k-1
**** Convocatoria de proyectos de fin de carrera para el desarrollo
Sigue existiendo?
***** Descripción
***** Convocatoria k
***** Convocatoria k-1
**** Convocatoria de ayudas de viaje de cooperación
***** 1-4 meses
Enlace a la página de UPM
***** 4-6 meses
Enlace a la página de UPM
**** Programas de estancias cortas
***** Athens
Idea: coger la introducción y meter en la página de listado. Luego las convocatorias poner en otra página
****** Descripción
El programa ATHENS ....
****** Convocatoria k
Nueva página con la convocatoria 2017-2018
****** Convocatoria k-1
***** BEST
****** Descripción
Crear una pequeña introducción y meter el enlace a su página, que es lo que hay hoy
*** Programa nacional Sicue
Quitar de esa página y poner en otra la parte específica (Convocatoria de 2017-2018)
**** Descripción corta
***** Convocatoria k
***** Convocatoria k-1
*** Acuerdos bilaterales y acuerdos de doble diploma de máster
**** Descripción
La ETSIINF mantiene acuerdos ....
**** Convocatoria k
Página (basada en la actual) con destinos, plazos y todo
*** Becas Tokyo Institute of Technology (Japón)
**** Descripción
**** Convocatoria k
Enlace a upm.es
*** Becas Iberoamérica - Santander Universidades - son becas o programas académicos?
*** Becas fórmula Santander - son becas o programas académicos?
*** Becas Santander-CRUE de movilidad Iberoamericana - son becas o programas académicos?
*** Becas UPM-Santander - son becas o programas académicos?
** Programas de prácticas en empresa en el exterior
*** Vulcanus
*** Becas ARGO
*** Becas Faro Global
*** Becas Goya-Mundus
*** Movilidad para prácticas en empresas a través del programa ERASMUS
**** Plataforma para ofertas de prácticas ERASMUS+
** Otros programas
*** Programas de voluntariado
** Información de interés sobre idiomas
Explicar mejor la necesidad de esta parte
*** PROLINTER
*** Programa de Formación linguística para los participantes en los programas de movilidad
*** Exámenes de acreditación externa TOEIC/TFI
*** Lenguas del mundo en B-learning
*** Certificados reconocidos nacional e internacionalmente
- Inglés
- Alemán
- Francés
- ...???
