#+HTML_HEAD: <style type="text/css"> <!--/*--><![CDATA[/*><!--*/ .title { display: none; } /*]]>*/--> </style>
#+OPTIONS: num:nil

* Programas de movilidad para alumnos externos
En primer lugar queremos dar la bienvenida a la Escuela Técnica Superior de Ingenieros Informáticos - ETSIINF - (antes Facultad de Informática), Universidad Politécnica de Madrid, a todos los alumnos de intercambio que han decidido hacer una estancia con nosotros. Estamos realmente encantados de que hayáis elegido nuestra Facultad para llevar a cabo vuestro programa de intercambio y estamos convencidos de que vuestra estancia de estudios así como  vuestra estancia en España será muy agradable y valiosa para vuestro futuro académico, profesional y personal.

En esta página se incluye información útil para los alumnos extranjeros que deseen pasar una estancia de estudios en la ETSIINF mediante programas de intercambio.

Si la información que buscas no está aquí, contacta con la [[http://fi.upm.es/?pagina=286][Oficina de Relaciones Externas (OREX)]] y gustosamente te atenderemos.
* Acceso a la ETSIINF
Los estudiantes extranjeros interesados en realizar una estancia en la ETSIINF deberán contactar con la oficina internacional de su universidad o centro de origen y verificar si existe o no convenio de intercambio de estudiantes.

En caso de existir convenio, los estudiantes podrán solicitar su admisión a través de sus oficinas internacionales.

Si no existe convenio deben consultar con sus oficinas internacionales sobre la posibilidad de establecer uno. De no ser posible, cabe la posibilidad de ser admitido como alumno visitante (sin convenio) ([[http://www.upm.es/sfs/Rectorado/Vicerrectorado%20de%20Relaciones%20Internacionales/Resto%20del%20Mundo/normativa_estudiantes_visitantes.pdf][Normativa]]).

** Plazos de solicitud de admisión
- *1 Junio*: para estancias de curso completo y del semestre de otoño
- *1 Diciembre*: para estancias durante el semestre de primavera

** Documentos para la solicitud
Las solicitudes deben ser remitidas junto con la siguiente documentación por el coordinador o la oficina internacional de la universidad de origen a la Oficina de la Relaciones Externas (OREX) de la ETSIINF.

Documentos para *todos* los programas de intercambio:
- Carta de motivación
- Curriculum vitae
- Certificado oficial de calificaciones
- Fotocopia de pasaporte o tarjeta de identidad
- 1 fotografía digitalizada

Documentos específicos para el programa *ERASMUS+*:
- [[http://fi.upm.es/docs/servicios/tramites/432_EPP_2016_17_learning_agreement_studies_ver2016_3.docx][Contrato de estudios]]
- [[http://www.upm.es/sfs/Rectorado/Vicerrectorado%20de%20Alumnos/Extension%20Universitaria/Intercambios:%20movilidad%20de%20estudiantes/Erasmus/Extranjeros/FORMULARIO%20ALTA%20EXTRANJEROS%202014-2015.pdf][Formulario de alta (A rellenar en el momento de  la incorporación)]]

Documentos específicos para el programa *SMILE*:
- [[https://vri5.rec.upm.es/magalhaes/Files/SMILE%20Student%20Application-Form.pdf][Solicitud de admisión]]
- [[https://vri5.rec.upm.es/magalhaes/Files/SMILE%20Student%20Learning-Agreement.pdf][Contrato de estudios]]

Documentos específicos para el programa de *acuerdos bilaterales*:
- [[http://fi.upm.es/docs/servicios/tramites/432_2014_Solicitud%20alumnos%20con%20convenio.pdf][Solicitud de admisión]]
- [[http://fi.upm.es/docs/servicios/tramites/432_Contrato%20de%20estudios%20CON%20CONVENIO2010-11.doc][Contrato de estudios]]

Documentos específicos para alumnos *visitantes* (sin convenio):
- [[http://www.upm.es/sfs/Rectorado/Vicerrectorado%20de%20Relaciones%20Internacionales/Resto%20del%20Mundo/Impreso_alumnos_visitantes.pdf][Solicitud de admisión]]
- [[http://fi.upm.es/docs/servicios/tramites/432_Contrato%20de%20estudios%20VISITANTES%20SC.doc][Contrato de estudios]]

** Admisión

Una vez recibida la solicitud de admisión junto con toda la documentación señalada, la Oficina de Relaciones Externas (OREX) de la ETSIINF procederá a estudiar y en su caso admitir a los estudiantes. En un plazo no superior a cuatro semanas desde la recepción de la solicitud, se le comunicará al alumno la admisión o no al programa. Una vez admitido en el programa, el alumno recibirá una carta de admisión por parte de la ETSIINF, junto con el contrato de estudios firmado e información útil para alumnos de intercambio.

** Visados

Los alumnos no europeos deben solicitar visado para entrar en España. La solicitud deben realizarla en la Embajada o Consulado español del pais de origen.

** Seguros

Los alumnos europeos deberán proveerse de la Tarjeta Sanitaria Europea en sus paises de origen o deben contratar un seguro privado.

Los alumnos no europeos deberán contratar un seguro privado con repatriación en sus paises de origen a la hora de tramitar el visado.

La UPM ofrece la posibilidad de contratar el seguro [[http://oncampus.es/][ONCAMPUS]].

* Llegada a Madrid y primeros pasos

La ETSIINF se encuetra en el Campus de Montegancedo.

[[http://fi.upm.es/?pagina=166][Como llegar a la ETSIINF]]

Una vez que el alumno ha llegado a Madrid, una de las primeras cosas que debe hacer es visitar la Oficina de Relaciones Externas (OREX)de la ETSIINF para registrarse. Allí el alumno recibirá toda la información necesaria para convertirse en un alumno de la ETSIINF. La OREX es la que se encarga de todos los trámites relacionados con  alumnos en programas de movilidad.

* Programas de estudios
En la actualidad, en la ETSIINF se imparten los siguientes programas de estudios:
- [[http://fi.upm.es/?id=gradoingenieriainformatica][Graduado en Ingeniería Informática]]
- [[http://fi.upm.es/?id=gradomatematicasinformatica][Graduado en Matemáticas e Informática]]
- [[http://fi.upm.es/?pagina=1645][Máster Universitario en Ingeniería Informática]], de orientación profesional
- [[http://fi.upm.es/es/europeanmasteronsoftwareengineering][Máster Universitario en Ingeniería del Software - European Master on Software Engineering]]
  - Para cursar asignaturas de este máster se requiere nivel de inglés B2 o superior, que puede ser certificado a través de títulos oficiales (IELTS, FCE, CAE, CPE, TOEFL o TOEIC) o a través de certificación de la universidad de origen.
- [[http://www.dia.fi.upm.es/masteria/?q=es/MUIA][Máster Universitario en Inteligencia Artificial]], orientado a la investigación. [[http://fi.upm.es/?id=masterinteligenciaartificial][(enlace interno)]]
- [[http://muss.fi.upm.es/][Máster Universitario en Software y Sistemas]], orientado a la investigación [[http://fi.upm.es/?id=mastersoftwareysistemas][(enlace interno)]]

Todos los programas están estructurados en asignaturas semestrales y créditos ECTS.

** Calendario
Para cada curso coexisten varios calendarios activos en función del programa de estudios. Consultar cada programa para ver calendario adecuado.

** Horarios de clase
Los horarios de clase son fijos y no es posible cambiarlos. Es responsabilidad del alumno el confeccionar un programa de estudios en el que no haya solapamientos de horarios.

** Exámenes
Las fecha y horarios de exámenes son fijos y no es posible cambiarlos.

No es necesario registrarse para realizar un examen. Una vez que el alumno está oficialmente matriculado tiene derecho a dos convocatorias de exámen, una ordinaria (Enero o Junio) y otra extraordinaria (Julio).

Los alumnos que opten por la modalidad de examen final deben comunicarlo al profesor-coordinador de la asignatura en un plazo que se informa en la guía de la misma.

Se recomienda consultar fechas y horarios de ambas convocatorias en los respectivos programas de estudios (guía de asignatura).

** Matrícula
La matrícula de todos los alumnos de intercambio será realizada exclusivamente por la Oficina de Relaciones Externas del centro.

Para realizar la matrícula es necesario que el Acuerdo Académico esté debidamente cumplimentado y refleje las asignaturas que el alumno realmente quiere cursar. Si fuera necesario realizar cambios al Acuerdo Académico inicial, éstos podrán hacerse en un periodo máximo de diez días desde el comienzo del curso. Durante este periodo los alumnos de intercambio deben comunicar a la mayor brevedad posible dichos cambios a la Oficina de Relaciones Externas para rehacer el Acuerdo Académico y enviarlo a su universidad de origen, o por el contrario, deben comunicar  que el contenido inicial del Acuerdo Académico es válido y correcto. Sin este requisito NO es posible realizar la matrícula.

Una vez realizada la matrícula no es posible modificarla a lo largo del curso, por lo que se recomienda encarecidamente que el alumno se asegure de que las asignaturas que figuran en el Acuerdo Académico son las que realmente quiere cursar, que pertenecen al semestre adecuado y que el horario no se solapa con otras asignaturas.

La matrícula se realizará por semestres. Cada semestre tiene un periodo de matrícula (Julio-Septiembre y Enero-Febrero).

Una vez realizada la matrícula se avisará al alumno por correo electrónico para que solicite de forma on-line, cuenta de correo electrónico @alumnos.upm.es. Esta dirección de correo electrónico es imprescindible para acceder a los servicios en red de la UPM (Politécnica virtual, plataformas de teleenseñanza, red inalámbrica, correo electrónico, etc.).

** Lengua en la que se imparten las clases

Las clases son impartidas mayoritariamente en español, en especial en los programas de grado. Algunos programas de master imparten clases en inglés y español. Para conocer la lengua en que se imparten las clases hay que consultar cada asignatura en su guia de aprendizaje.

Por todo lo anterior y para que el alumno pueda seguir con normalidad y aprovechamiento las clases, se recomienda encarecidamente que los alumnos posean un nivel de español de B1 (Marco Comun Europeo de Referencia de las Lenguas) certificado oficialmente, o  por  la propia universidad de origen. Aquellos alumnos que no puedan acreditar dicho nivel, deberan asistir al programa de Español organizado por [[http://www.upm.es/institucional/Estudiantes/Movilidad/LenguasInternacionalizacion][PROLINTER UPM]] para los alumnos internacionales.

* Cursos de español

La UPM a través del [[http://www.upm.es/institucional/Estudiantes/Movilidad/LenguasInternacionalizacion][Programa de Lenguas para la Internacionalización (PROLINTER)]] ofrece una alta variedad de cursos de español para los estudiantes de intercambio que van a disfrutar de una estancia en cualquiera de sus centros.

Existen muchas razones para aprender español. La primera de ellas es que la mayoría de los programas de estudio en la ETSIINF son impartidos en español por lo que es muy recomendable tomar algún curso de español para poder seguir las clases con el adecuado aprovechamiento. En segundo lugar, el español es una herramienta esencial para tratar y resolver asuntos de la vida cotidiana con españoles. Y por último pero no por ello menos importante, el español es una de las lenguas más habladas en el mundo, por ello, vale la pena aprovechar la oportunidad de aprender y practicar español durante vuestra estancia en Madrid.

Los alumnos de intercambio tienen varias programas de español para elegir: cursos de verano, cursos intensivos, cursos regulares aplicados a la ciencia y la tecnología, examenes DELE, etc.. Asimismo existen precios especiales para los alumnos de intercambio.

Más információn sobre calendario, horarios, plazos de solicitud, etc. en [[http://www.upm.es/institucional/Estudiantes/Movilidad/LenguasInternacionalizacion][PROLINTER]].

* Alojamiento
La ETSIINF no dispone de servicio de alojamiento tales como residencias de estudiantes o colegios mayores, pero puedes encontrar información sobre alojamiento en la [[http://www.upm.es/institucional/Estudiantes/Atencion/AlojamientoEstudiantes][web]] de la UPM y en (>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<).

Tienes que tener en cuenta que Madrid es una ciudad muy cara para vivir, por ello debes estimar una cantidad aproximada 350€ por mes por una habitación en piso compartido, más una cantidad similar para dejar en depósito. Los precios varían dependiendo de la zona.

* Grupos y sitios de noticias
Facebook: https://www.facebook.com/ETSIINF

Twitter: @informaticaupm

** Otros sitios con información de interés
- [[http://www.upm.es/sfs/Rectorado/Vicerrectorado%20de%20Alumnos/Extension%20Universitaria/Intercambios:%20movilidad%20de%20estudiantes/Erasmus/Extranjeros/GUIA%20PARA%20ESTUDIANTES%20EXTRANJEROS%20-%20SPANISH.pdf][Guia para estudiantes extranjeros UPM]]
- [[http://www.upm.es/portal/site/institucional/template.PAGE/menuitem.ca8d5a1f6c6bb42aad77b13bdffb46a8/?javax.portlet.tpst=ec9cfb82dd1810f48851ac10907c46a8&javax.portlet.prp_ec9cfb82dd1810f48851ac10907c46a8=opcion%3DvistaCentros&javax.portlet.begCacheTok=com.vignette.cachetoken&javax.portlet.endCacheTok=com.vignette.cachetoken&vgnextoid=598350078572f110VgnVCM10000009c7648aRCRD][Asociaciones de estudiantes en la UPM]]
- [[http://fi.upm.es/?pagina=18][Asociaciones de estudiantes en la ETSIINF]]
- [[http://www.upm.es/DelegacionAlumnos/Delegacion/E_Delegacion][Delegación de Alumnos UPM]]
- [[http://da.fi.upm.es/][Delegación de Alumnos ESTIINF]]
- [[http://www.upm.es/institucional/UPM/Actividades_Culturales/Acceso_Actividades][Actividades culturales UPM]]
- [[http://www.upm.es/institucional/UPM/Actividades_Culturales/Aula_Cultura][Aula de cultura]]
- [[http://www.upm.es/institucional/UPM/MuseosUPM][Museos y colecciones UPM]]
- [[http://www.mhi.fi.upm.es/][Museo Histórico de la Informática]]
- [[http://www.upm.es/institucional/UPM/Deportes][Actividades deportivas UPM]]
- [[http://fi.upm.es/?pagina=229][Instalaciones deportivas en la ETSIINF]]
- [[http://www.upm.es/institucional/Estudiantes/CompeticionesEstudiantes][Competiciones de estudiantes UPM]]



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
He terminado esta pagina por ahora y seguir con las siguientes
